name: Release

on:
  push:
    tags:
      - 'v*'

# Add permissions block
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Compile
        run: npm run compile
        
      - name: Package Extension
        run: |
          npm install -g @vscode/vsce
          vsce package
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.vsix
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 